### ISSUE TITLE
Integration of VerotelRUM with NestJS and Angular Environment

### ISSUE THREAD

**Issue by trol98** [verotel/flexpay-php-client#13]
Hello,

I am currently working on integrating VerotelRUM into our application, which is based on a NestJS and Angular architecture. I have observed that VerotelRUM appears to be optimized for use in a traditional PHP environment.

Could you please provide guidance on how we might effectively integrate this product within our ecosystem? One approach I am considering involves monitoring the requests made by Verotel to our local instance of VerotelRUM. In response to these calls, we could use our NestJS endpoints handle the new state of RUM.

Any insights or recommendations on this integration would be greatly appreciated.

Thank you.

**Comment by PunchyRascal** [comment]
Hi there, 

before answering your question - did you consider using FlexPay instead of RUM?

FlexPay is a modern interface for payments with callbacks and flexible interface (payment amount, description etc.), whereas RUM is mainly intended for merchants who want to integrate pre-defined subscriptions into simple Apache-based member area.

When creating a website in Control center, you can choose whether to use FlexPay or RUM system.

As for the JS integration, there is no official SDK as of now, but the protocol for FlexPay is fairly straightforward - see the documentation at https://controlcenter.verotel.com/flexpay-doc/#flexpay-documentation

Let me know if you need more info!

**Comment by trol98** [comment]
Thank you for your prompt response; I truly appreciate it.

Initially, I was leaning towards using FlexPay, but ultimately I decided to integrate RUM, given that I am opting for the Verotel Basic plan. However, I find myself a bit confused regarding the information provided on the Verotel website.

Specifically, I noticed a discrepancy between [this page](https://www.verotel.com/en/productchoice.html) and [this page](https://www.verotel.com/en/pricechart.html). The second page indicates that the "Verotel FlexPay API" is available with the Basic plan, while the first page states that "Verotel FlexPay" is not available with the Basic plan.

Could you please help clarify this confusion for me?

Thank you for your assistance.

**Comment by PunchyRascal** [comment]
Thanks for pointing out the discrepancy on the website (we'll fix that). 

FlexPay is available for all plans, so you can use it on Basic, too, no need to revert to RUM.

**Comment by trol98** [comment]
Thank you for all the help 🙏
